favorite={}
name=input("enter the friend's name: ")
lang=input("enter your friend's favorite language: ")
favorite.update({name:lang})
name=input("enter the friend's name: ")
lang=input("enter your friend's favorite language: ")
favorite.update({name:lang})
name=input("enter the friend's name: ")
lang=input("enter your friend's favorite language: ")
favorite.update({name:lang})
name=input("enter the friend's name: ")
lang=input("enter your friend's favorite language: ")
favorite.update({name:lang})
print(favorite)