numbers=set()
n1=int(input("enter the first number: "))
n2=int(input("enter the second number: "))
n3=int(input("enter the third number: "))
n4=int(input("enter the fourth number: "))
n5=int(input("enter the fifth number: "))
n6=int(input("enter the sixth number: "))
numbers.add(n1)
numbers.add(n2)
numbers.add(n3)
numbers.add(n4)
numbers.add(n5)
numbers.add(n6)
print(numbers)